### PR TITLE
Use updated ament_index_cpp interfaces, re-add rolling

### LINKED ISSUE #228: Build error rolling/testing: get_resources is not a member of ament_index_cpp
```

  --- stderr: mujoco_ros2_control
  CMake Warning at CMakeLists.txt:57 (message):
    MUJOCO_DEP_VERSION_lodepng not exported by mujoco_vendor; fetching lodepng
    HEAD
  
  
  CMake Warning (dev) at /usr/share/cmake-4.2/Modules/FetchContent.cmake:1963 (message):
    Calling FetchContent_Populate(lodepng) is deprecated, call
    FetchContent_MakeAvailable(lodepng) instead.  Policy CMP0169 can be set to
    OLD to allow FetchContent_Populate(lodepng) to be called directly for now,
    but the ability to call it with declared details will be removed completely
    in a future version.
  Call Stack (most recent call first):
    CMakeLists.txt:67 (FetchContent_Populate)
  This warning is for project developers.  Use -Wno-dev to suppress it.
  
  /usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py:90: SetuptoolsDeprecationWarning: setup.py install is deprecated.
  !!
  
          ********************************************************************************
          Please avoid running ``setup.py`` directly.
          Instead, use pypa/build, pypa/installer or other
          standards-based tools.
  
          See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
          ********************************************************************************
  
  !!
    self.initialize_options()
  /home/runner/work/ros2_control_ci/ros2_control_ci/.work/target_ws/src/ros-controls/mujoco_ros2_control/mujoco_ros2_control/src/mujoco_simulation.cpp: In function ‘void mujoco_ros2_control::scanPluginLibraries()’:
  /home/runner/work/ros2_control_ci/ros2_control_ci/.work/target_ws/src/ros-controls/mujoco_ros2_control/mujoco_ros2_control/src/mujoco_simulation.cpp:319:35: error: ‘get_resources’ is not a member of ‘ament_index_cpp’; did you mean ‘get_resource’?
    319 |   auto plugins = ament_index_cpp::get_resources("mujoco_plugins");
        |                                   ^~~~~~~~~~~~~
        |                                   get_resource
  gmake[2]: *** [CMakeFiles/mujoco_ros2_control.dir/build.make:79: CMakeFiles/mujoco_ros2_control.dir/src/mujoco_simulation.cpp.o] Error 1
  gmake[1]: *** [CMakeFiles/Makefile2:299: CMakeFiles/mujoco_ros2_control.dir/all] Error 2
  gmake: *** [Makefile:146: all] Error 2
  ---
  Failed   <<< mujoco_ros2_control [25.9s, exited with code 2]

```

https://github.com/ros-controls/ros2_control_ci/issues/858
From https://github.com/ros-controls/mujoco_ros2_control/pull/205?

### PR DESCRIPTION
**Pull request by eholum-nasa**
Fixes #228 and #178 

Sorry for the bother, this was introduced in #205 because I was silly and didn't realize those function names were changing. I believe this handles the updated API.

The latest rolling images from dockerhub (last week) also seem to have resolved the rosdep issues. @christophfroehlich hopefully that means these are just good to go? I propose just re-enabling rolling so that we can catch issues like this sooner...

In any case, seems good!

### CODE REVIEW

**Review by scastro-nasa — APPROVED** [review]
ament just be breaking compatibility for funsies, `get_package_share_folder()` is also being changed which is coming for us all...

**Comment by eholum-nasa** [comment]
> get_package_share_folder() is also being changed which is coming for us all...

paaaaaaaaaaaaaaaaaaaaaaaiiiiiiiiiiiiinnnnnnnnnnnnnn

**Review by saikishor — APPROVED** [review]
