### PR TITLE
Add macro check using realtime_tools_MAJOR_VERSION

### LINKED ISSUE #180: [CI] Rolling-on-humble build is broken
https://github.com/ros-controls/ros2_control_ci/actions/runs/25128549610/job/73648269163?pr=761
```
  /home/runner/work/ros2_control_ci/ros2_control_ci/.work/target_ws/src/ros-controls/mujoco_ros2_control/mujoco_ros2_control_plugins/src/external_wrench_plugin.cpp: In member function ‘void mujoco_ros2_control_plugins::ExternalWrenchPlugin::publish_markers()’:
  /home/runner/work/ros2_control_ci/ros2_control_ci/.work/target_ws/src/ros-controls/mujoco_ros2_control/mujoco_ros2_control_plugins/src/external_wrench_plugin.cpp:285:16: error: ‘class realtime_tools::RealtimePublisher<visualization_msgs::msg::MarkerArray_<std::allocator<void> > >’ has no member named ‘tryPublish’; did you mean ‘try_publish’?
    285 |   marker_pub_->tryPublish(msg);
        |                ^~~~~~~~~~
        |                try_publish
```

Introduced with #165

Conditional on RCLCPP_VERSION_MAJOR
https://github.com/ros-controls/mujoco_ros2_control/blob/dc158b4700d1d675a5f636b6b63e876db693bccd/mujoco_ros2_control_plugins/src/external_wrench_plugin.cpp#L282-L286

should be changed to ROS_DISTRO_HUMBLE like here
https://github.com/ros-controls/mujoco_ros2_control/blob/dc158b4700d1d675a5f636b6b63e876db693bccd/mujoco_ros2_control/src/mujoco_system_interface.cpp#L1504-L1508

As an alternative, I can deactivate the build of mujoco_ros2_control in the compatibilty build.

### PR DESCRIPTION
**Pull request by saikishor**
Fixes #180

### CODE REVIEW

**Comment by saikishor** [comment]
https://github.com/ros-controls/realtime_tools/blob/0749ec2a6ec2cd8b11b305796928219c8e70077e/realtime_tools/include/realtime_tools/realtime_publisher.hpp#L163-L176

The changes exist already from realtime_tools 3.x.x, so this fix should be good

**Review by eholum-nasa — APPROVED** [review]
Will probably have to defer to @christophfroehlich but this makes sense to me at least?

**Review by christophfroehlich — APPROVED** [review]
Thank you!
